target("pyuipc")
    on_load(function (target)
        target:set("kind", "shared")
        target:set("extension", ".pyd")
    end)
    add_files("pyuipc/**.cpp")
    add_deps("uipc_uipc")
    add_includedirs(".")
    add_packages("pybind11")
    add_packages("python")