name: Manual Hotfix Publish
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The Run ID of the failed upload build'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download Artifacts from previous run
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          run-id: ${{ github.event.inputs.run_id }} # Uses artifacts from the old run
          pattern: pyuipc-*
          merge-multiple: true
          path: wheelhouse

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # release/v1
        with:
          packages-dir: wheelhouse
          skip-existing: true
          attestations: true
