
// > Squared Version
// > D := d*d

template <typename T>
__host__ __device__ void KappaBarrierWithThickness(
    T& R, const T& kappa, const T& D, const T& dHat, const T& xi)
{
    /*****************************************************************************************************************************
Function generated by SymEigen.py 
Author: MuGdxy
GitHub: https://github.com/MuGdxy/SymEigen
E-Mail: lxy819469559@gmail.com
******************************************************************************************************************************
LaTeX expression:
//tex:$$R = - \kappa \left(D - \hat{d}^{2} - 2 \hat{d} \xi - \xi^{2}\right)^{2} \log{\left(\frac{D - \xi^{2}}{\hat{d}^{2} + 2 \hat{d} \xi} \right)}$$

Symbol Name Mapping:
kappa:
    -> {}
    -> Matrix([[kappa]])
D:
    -> {}
    -> Matrix([[D]])
dHat:
    -> {}
    -> Matrix([[dHat]])
xi:
    -> {}
    -> Matrix([[xi]])
*****************************************************************************************************************************/
    /* Sub Exprs */
    auto x0 = std::pow(xi, 2);
    auto x1 = std::pow(dHat, 2) + 2 * dHat * xi;
    /* Simplified Expr */
    R = -kappa * std::pow(D - x0 - x1, 2) * log((D - x0) / x1);
}
template <typename T>
__host__ __device__ void dKappaBarrierWithThicknessdD(
    T& R, const T& kappa, const T& D, const T& dHat, const T& xi)
{
    /*****************************************************************************************************************************
Function generated by SymEigen.py 
Author: MuGdxy
GitHub: https://github.com/MuGdxy/SymEigen
E-Mail: lxy819469559@gmail.com
******************************************************************************************************************************
LaTeX expression:
//tex:$$R = - \kappa \left(2 D - 2 \hat{d}^{2} - 4 \hat{d} \xi - 2 \xi^{2}\right) \log{\left(\frac{D - \xi^{2}}{\hat{d}^{2} + 2 \hat{d} \xi} \right)} - \frac{\kappa \left(D - \hat{d}^{2} - 2 \hat{d} \xi - \xi^{2}\right)^{2}}{D - \xi^{2}}$$

Symbol Name Mapping:
kappa:
    -> {}
    -> Matrix([[kappa]])
D:
    -> {}
    -> Matrix([[D]])
dHat:
    -> {}
    -> Matrix([[dHat]])
xi:
    -> {}
    -> Matrix([[xi]])
*****************************************************************************************************************************/
    /* Sub Exprs */
    auto x0 = std::pow(xi, 2);
    auto x1 = D - x0;
    auto x2 = std::pow(dHat, 2);
    auto x3 = dHat * xi;
    auto x4 = x2 + 2 * x3;
    /* Simplified Expr */
    R = -kappa * (2 * D - 2 * x0 - 2 * x2 - 4 * x3) * log(x1 / x4)
        - kappa * std::pow(D - x0 - x4, 2) / x1;
}
template <typename T>
__host__ __device__ void ddKappaBarrierWithThicknessddD(
    T& R, const T& kappa, const T& D, const T& dHat, const T& xi)
{
    /*****************************************************************************************************************************
Function generated by SymEigen.py 
Author: MuGdxy
GitHub: https://github.com/MuGdxy/SymEigen
E-Mail: lxy819469559@gmail.com
******************************************************************************************************************************
LaTeX expression:
//tex:$$R = - 2 \kappa \log{\left(\frac{D - \xi^{2}}{\hat{d}^{2} + 2 \hat{d} \xi} \right)} - \frac{2 \kappa \left(2 D - 2 \hat{d}^{2} - 4 \hat{d} \xi - 2 \xi^{2}\right)}{D - \xi^{2}} + \frac{\kappa \left(D - \hat{d}^{2} - 2 \hat{d} \xi - \xi^{2}\right)^{2}}{\left(D - \xi^{2}\right)^{2}}$$

Symbol Name Mapping:
kappa:
    -> {}
    -> Matrix([[kappa]])
D:
    -> {}
    -> Matrix([[D]])
dHat:
    -> {}
    -> Matrix([[dHat]])
xi:
    -> {}
    -> Matrix([[xi]])
*****************************************************************************************************************************/
    /* Sub Exprs */
    auto x0 = std::pow(xi, 2);
    auto x1 = D - x0;
    auto x2 = std::pow(dHat, 2);
    auto x3 = dHat * xi;
    auto x4 = x2 + 2 * x3;
    auto x5 = 2 * kappa;
    /* Simplified Expr */
    R = kappa * std::pow(D - x0 - x4, 2) / std::pow(x1, 2) - x5 * log(x1 / x4)
        - x5 * (2 * D - 2 * x0 - 2 * x2 - 4 * x3) / x1;
}
template <typename T>
__host__ __device__ void KappaBarrierLog2(T& R, const T& kappa, const T& D, const T& dHat)
{
    /*****************************************************************************************************************************
Function generated by SymEigen.py 
Author: MuGdxy
GitHub: https://github.com/MuGdxy/SymEigen
E-Mail: lxy819469559@gmail.com
******************************************************************************************************************************
LaTeX expression:
//tex:$$R = \kappa \left(D - \hat{d}^{2}\right)^{2} \log{\left(\frac{D}{\hat{d}^{2}} \right)}^{2}$$

Symbol Name Mapping:
kappa:
    -> {}
    -> Matrix([[kappa]])
D:
    -> {}
    -> Matrix([[D]])
dHat:
    -> {}
    -> Matrix([[dHat]])
*****************************************************************************************************************************/
    /* Sub Exprs */
    auto x0 = std::pow(dHat, 2);
    /* Simplified Expr */
    R = kappa * std::pow(D - x0, 2) * std::pow(log(D / x0), 2);
}
template <typename T>
__host__ __device__ void dKappaBarrierLog2dD(T& R, const T& kappa, const T& D, const T& dHat)
{
    /*****************************************************************************************************************************
Function generated by SymEigen.py 
Author: MuGdxy
GitHub: https://github.com/MuGdxy/SymEigen
E-Mail: lxy819469559@gmail.com
******************************************************************************************************************************
LaTeX expression:
//tex:$$R = \kappa \left(2 D - 2 \hat{d}^{2}\right) \log{\left(\frac{D}{\hat{d}^{2}} \right)}^{2} + \frac{2 \kappa \left(D - \hat{d}^{2}\right)^{2} \log{\left(\frac{D}{\hat{d}^{2}} \right)}}{D}$$

Symbol Name Mapping:
kappa:
    -> {}
    -> Matrix([[kappa]])
D:
    -> {}
    -> Matrix([[D]])
dHat:
    -> {}
    -> Matrix([[dHat]])
*****************************************************************************************************************************/
    /* Sub Exprs */
    auto x0 = std::pow(dHat, 2);
    auto x1 = log(D / x0);
    /* Simplified Expr */
    R = kappa * std::pow(x1, 2) * (2 * D - 2 * x0)
        + 2 * kappa * x1 * std::pow(D - x0, 2) / D;
}
template <typename T>
__host__ __device__ void ddKappaBarrierLog2ddD(T& R, const T& kappa, const T& D, const T& dHat)
{
    /*****************************************************************************************************************************
Function generated by SymEigen.py 
Author: MuGdxy
GitHub: https://github.com/MuGdxy/SymEigen
E-Mail: lxy819469559@gmail.com
******************************************************************************************************************************
LaTeX expression:
//tex:$$R = 2 \kappa \log{\left(\frac{D}{\hat{d}^{2}} \right)}^{2} + \frac{4 \kappa \left(2 D - 2 \hat{d}^{2}\right) \log{\left(\frac{D}{\hat{d}^{2}} \right)}}{D} - \frac{2 \kappa \left(D - \hat{d}^{2}\right)^{2} \log{\left(\frac{D}{\hat{d}^{2}} \right)}}{D^{2}} + \frac{2 \kappa \left(D - \hat{d}^{2}\right)^{2}}{D^{2}}$$

Symbol Name Mapping:
kappa:
    -> {}
    -> Matrix([[kappa]])
D:
    -> {}
    -> Matrix([[D]])
dHat:
    -> {}
    -> Matrix([[dHat]])
*****************************************************************************************************************************/
    /* Sub Exprs */
    auto x0 = std::pow(dHat, 2);
    auto x1 = log(D / x0);
    auto x2 = 2 * kappa;
    auto x3 = x2 * std::pow(D - x0, 2) / std::pow(D, 2);
    /* Simplified Expr */
    R = std::pow(x1, 2) * x2 - x1 * x3 + x3 + 4 * kappa * x1 * (2 * D - 2 * x0) / D;
}
template <typename T>
__host__ __device__ void KappaBarrierLog2WithThickness(
    T& R, const T& kappa, const T& D, const T& dHat, const T& xi)
{
    /*****************************************************************************************************************************
Function generated by SymEigen.py 
Author: MuGdxy
GitHub: https://github.com/MuGdxy/SymEigen
E-Mail: lxy819469559@gmail.com
******************************************************************************************************************************
LaTeX expression:
//tex:$$R = \kappa \left(D - \hat{d}^{2} - 2 \hat{d} \xi - \xi^{2}\right)^{2} \log{\left(\frac{D - \xi^{2}}{\hat{d}^{2} + 2 \hat{d} \xi} \right)}^{2}$$

Symbol Name Mapping:
kappa:
    -> {}
    -> Matrix([[kappa]])
D:
    -> {}
    -> Matrix([[D]])
dHat:
    -> {}
    -> Matrix([[dHat]])
xi:
    -> {}
    -> Matrix([[xi]])
*****************************************************************************************************************************/
    /* Sub Exprs */
    auto x0 = std::pow(xi, 2);
    auto x1 = std::pow(dHat, 2) + 2 * dHat * xi;
    /* Simplified Expr */
    R = kappa * std::pow(D - x0 - x1, 2) * std::pow(log((D - x0) / x1), 2);
}
template <typename T>
__host__ __device__ void dKappaBarrierLog2WithThicknessdD(
    T& R, const T& kappa, const T& D, const T& dHat, const T& xi)
{
    /*****************************************************************************************************************************
Function generated by SymEigen.py 
Author: MuGdxy
GitHub: https://github.com/MuGdxy/SymEigen
E-Mail: lxy819469559@gmail.com
******************************************************************************************************************************
LaTeX expression:
//tex:$$R = \kappa \left(2 D - 2 \hat{d}^{2} - 4 \hat{d} \xi - 2 \xi^{2}\right) \log{\left(\frac{D - \xi^{2}}{\hat{d}^{2} + 2 \hat{d} \xi} \right)}^{2} + \frac{2 \kappa \left(D - \hat{d}^{2} - 2 \hat{d} \xi - \xi^{2}\right)^{2} \log{\left(\frac{D - \xi^{2}}{\hat{d}^{2} + 2 \hat{d} \xi} \right)}}{D - \xi^{2}}$$

Symbol Name Mapping:
kappa:
    -> {}
    -> Matrix([[kappa]])
D:
    -> {}
    -> Matrix([[D]])
dHat:
    -> {}
    -> Matrix([[dHat]])
xi:
    -> {}
    -> Matrix([[xi]])
*****************************************************************************************************************************/
    /* Sub Exprs */
    auto x0 = dHat * xi;
    auto x1 = std::pow(dHat, 2);
    auto x2 = std::pow(xi, 2);
    auto x3 = D - x2;
    auto x4 = 2 * x0 + x1;
    auto x5 = log(x3 / x4);
    /* Simplified Expr */
    R = kappa * std::pow(x5, 2) * (2 * D - 4 * x0 - 2 * x1 - 2 * x2)
        + 2 * kappa * x5 * std::pow(D - x2 - x4, 2) / x3;
}
template <typename T>
__host__ __device__ void ddKappaBarrierLog2WithThicknessddD(
    T& R, const T& kappa, const T& D, const T& dHat, const T& xi)
{
    /*****************************************************************************************************************************
Function generated by SymEigen.py 
Author: MuGdxy
GitHub: https://github.com/MuGdxy/SymEigen
E-Mail: lxy819469559@gmail.com
******************************************************************************************************************************
LaTeX expression:
//tex:$$R = 2 \kappa \log{\left(\frac{D - \xi^{2}}{\hat{d}^{2} + 2 \hat{d} \xi} \right)}^{2} + \frac{4 \kappa \left(2 D - 2 \hat{d}^{2} - 4 \hat{d} \xi - 2 \xi^{2}\right) \log{\left(\frac{D - \xi^{2}}{\hat{d}^{2} + 2 \hat{d} \xi} \right)}}{D - \xi^{2}} - \frac{2 \kappa \left(D - \hat{d}^{2} - 2 \hat{d} \xi - \xi^{2}\right)^{2} \log{\left(\frac{D - \xi^{2}}{\hat{d}^{2} + 2 \hat{d} \xi} \right)}}{\left(D - \xi^{2}\right)^{2}} + \frac{2 \kappa \left(D - \hat{d}^{2} - 2 \hat{d} \xi - \xi^{2}\right)^{2}}{\left(D - \xi^{2}\right)^{2}}$$

Symbol Name Mapping:
kappa:
    -> {}
    -> Matrix([[kappa]])
D:
    -> {}
    -> Matrix([[D]])
dHat:
    -> {}
    -> Matrix([[dHat]])
xi:
    -> {}
    -> Matrix([[xi]])
*****************************************************************************************************************************/
    /* Sub Exprs */
    auto x0 = std::pow(xi, 2);
    auto x1 = D - x0;
    auto x2 = std::pow(dHat, 2);
    auto x3 = dHat * xi;
    auto x4 = x2 + 2 * x3;
    auto x5 = log(x1 / x4);
    auto x6 = 2 * kappa;
    auto x7 = x6 * std::pow(D - x0 - x4, 2) / std::pow(x1, 2);
    /* Simplified Expr */
    R = 4 * kappa * x5 * (2 * D - 2 * x0 - 2 * x2 - 4 * x3) / x1
        + std::pow(x5, 2) * x6 - x5 * x7 + x7;
}

/* Dispatcher: stiff log^2 barrier (Stiff-GIPC design). xi == 0 -> plain log^2 form;
 * xi > 0 -> log^2 on the thickness-shifted distance (D - xi^2), same active domain
 * (xi^2, (dHat+xi)^2) as the classic codim barrier. The classic log-with-thickness
 * functions (KappaBarrierWithThickness etc.) are kept for reference. */
template <typename T>
__host__ __device__ void KappaBarrier(T& R, const T& kappa, const T& D, const T& dHat, const T& xi)
{
    if(xi == 0.0)
        KappaBarrierLog2(R, kappa, D, dHat);
    else
        KappaBarrierLog2WithThickness(R, kappa, D, dHat, xi);
}
template <typename T>
__host__ __device__ void dKappaBarrierdD(T& R, const T& kappa, const T& D, const T& dHat, const T& xi)
{
    if(xi == 0.0)
        dKappaBarrierLog2dD(R, kappa, D, dHat);
    else
        dKappaBarrierLog2WithThicknessdD(R, kappa, D, dHat, xi);
}
template <typename T>
__host__ __device__ void ddKappaBarrierddD(T& R, const T& kappa, const T& D, const T& dHat, const T& xi)
{
    if(xi == 0.0)
        ddKappaBarrierLog2ddD(R, kappa, D, dHat);
    else
        ddKappaBarrierLog2WithThicknessddD(R, kappa, D, dHat, xi);
}
